"use client";

import { ArrowRight, Lightbulb, Sparkle } from "@phosphor-icons/react";

import type { BlockDefinition, BlockProps } from "@/lib/reports/registry";

/**
 * AI recommendation block — a standalone list of 1-5 prioritized
 * actions, generated by the LLM from the headline numbers of every
 * block above it in the report.
 *
 * The block itself has no editable user content in 3.3b — the prose
 * IS the AI summary. In 3.5 the user gets inline edits over the text.
 * The "Regenerate" affordance arrives with the right-rail Inspector
 * in 3.5; for now the block is read-only display.
 */

type AudienceTone = "internal" | "client" | "vendor";

interface ActionLink {
  id?: string;
  type?: string | null;
  priority?: string | null;
  title?: string | null;
  href?: string | null;
  requirement_code?: string | null;
  period_key?: string | null;
}

interface AiRecommendationConfig {
  based_on: string[];
  priority_count: number;
  audience_tone: AudienceTone;
}

interface AiRecommendationData {
  upstream_block_summaries: Array<{
    block_id: string;
    type: string;
    key_metric: unknown;
  }>;
  audience_tone: AudienceTone;
  priority_count: number;
  action_links?: ActionLink[];
}

export const aiRecommendationDefinition: Omit<
  BlockDefinition<AiRecommendationConfig, AiRecommendationData>,
  "Component"
> = {
  type: "ai_recommendation",
  label: "Recomendaciones de IA",
  icon: Lightbulb,
  description:
    "Lista priorizada de próximas acciones generada por la IA a partir de los bloques anteriores.",
  defaultConfig: {
    based_on: [],
    priority_count: 3,
    audience_tone: "internal",
  },
};

export function AiRecommendationBlock({
  block,
  editable,
}: BlockProps<AiRecommendationConfig, AiRecommendationData>) {
  const ai = block.ai_summary;
  const upstream = block.data?.upstream_block_summaries ?? [];
  const actionLinks = block.data?.action_links ?? [];

  return (
    <section
      className="space-y-3 py-2 print:break-inside-avoid"
      data-block-type="ai_recommendation"
    >
      {/* Authoring config (priorities / tone / inputs) is useful while
          editing but reads as machine telemetry to the report's audience,
          so it's hidden in read / story / print mode. */}
      {editable ? (
        <div className="cw-metadata-strip">
          <div>
            <span className="cw-eyebrow">Prioridades</span>
            <span className="font-mono text-[13px] text-[color:var(--text-primary)]">
              {block.config.priority_count}
            </span>
          </div>
          <div>
            <span className="cw-eyebrow">Tono</span>
            <span className="text-[13px] text-[color:var(--text-primary)]">
              {toneLabel(block.config.audience_tone)}
            </span>
          </div>
          <div>
            <span className="cw-eyebrow">Basado en</span>
            <span className="font-mono text-[11px] text-[color:var(--text-tertiary)]">
              {upstream.length} bloque{upstream.length === 1 ? "" : "s"}
            </span>
          </div>
        </div>
      ) : null}

      {ai && ai.text ? (
        <div className="rounded-md border border-[color:var(--status-ai-border)] bg-[color:var(--status-ai-bg)] p-4">
          <div className="mb-2 flex items-center gap-1.5 text-[11px] uppercase tracking-wide text-[color:var(--text-ai)]">
            <Sparkle className="h-3 w-3" weight="fill" aria-hidden="true" />
            <span>Generado por IA · Verificar antes de compartir</span>
          </div>
          <div
            className="cw-prose text-[14px] leading-relaxed text-[color:var(--text-primary)]"
            data-md-source="ai_recommendation"
          >
            {ai.text}
          </div>
          {actionLinks.length > 0 ? (
            <div className="mt-3 flex flex-wrap gap-2 print:hidden">
              {actionLinks.map((link, idx) =>
                link.href ? (
                  <a
                    key={link.id ?? `${link.href}-${idx}`}
                    href={link.href}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1 rounded-sm border border-[color:var(--status-ai-border)] bg-[color:var(--surface-page)] px-2.5 py-1 text-[12px] font-medium text-[color:var(--text-primary)] hover:bg-[color:var(--surface-hover)]"
                  >
                    {link.title ?? "Abrir acción"}
                    <ArrowRight className="h-3 w-3" aria-hidden="true" />
                  </a>
                ) : null,
              )}
            </div>
          ) : null}
        </div>
      ) : (
        <div className="rounded-md border border-dashed border-[color:var(--border-subtle)] p-6 text-center">
          <Lightbulb
            className="mx-auto mb-2 h-5 w-5 text-[color:var(--text-tertiary)]"
            weight="regular"
            aria-hidden="true"
          />
          <p className="text-[13px] text-[color:var(--text-secondary)]">
            Esperando que la IA genere recomendaciones a partir de los bloques
            anteriores.
          </p>
        </div>
      )}
    </section>
  );
}

function toneLabel(tone: AudienceTone): string {
  switch (tone) {
    case "internal":
      return "Interno";
    case "client":
      return "Cliente";
    case "vendor":
      return "Proveedor";
  }
}
