from __future__ import annotations

import logging
import traceback

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, RedirectResponse

from app.api.v1.router import api_router
from app.core.config import settings

log = logging.getLogger("checkwise.unhandled")


def _assert_critical_routes(app: FastAPI) -> None:
    """Fail boot if a deploy is missing routes the frontend depends on."""
    critical = {
        ("GET", f"{settings.API_V1_PREFIX}/portal/me"),
        ("POST", f"{settings.API_V1_PREFIX}/portal/enter"),
    }
    registered = {
        (method, getattr(route, "path", ""))
        for route in app.routes
        for method in (getattr(route, "methods", None) or set())
    }
    missing = sorted(critical - registered)
    if missing:
        rendered = ", ".join(f"{method} {path}" for method, path in missing)
        raise RuntimeError(f"Critical API route(s) not registered: {rendered}")


def create_app() -> FastAPI:
    # /docs, /redoc, /openapi.json leak the entire API surface to
    # anonymous callers. Off by default outside `CHECKWISE_ENV=local`;
    # ENABLE_API_DOCS=true is the explicit opt-in for any other tier.
    docs_on = settings.api_docs_enabled
    app = FastAPI(
        title=settings.PROJECT_NAME,
        version=settings.API_VERSION,
        description="API base para cumplimiento documental REPSE de CheckWise.",
        openapi_url="/openapi.json" if docs_on else None,
        docs_url="/docs" if docs_on else None,
        redoc_url="/redoc" if docs_on else None,
    )

    allowed_origins = settings.cors_origins_list

    # Audit P3-03 (2026-05-25) — tightened from ``["*"]`` to explicit
    # allowlists. Permissive wildcards weren't exploitable (every
    # state-changing endpoint enforces auth) but a buyer-audit
    # rightly flags them. Headers list covers every header any
    # CheckWise frontend (admin / client / portal) actually sends —
    # ``Authorization`` for JWT, ``X-Workspace-Token`` for the legacy
    # portal token path, plus the standard fetch / form-data headers.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=allowed_origins,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS"],
        allow_headers=[
            "Accept",
            "Accept-Language",
            "Authorization",
            "Content-Language",
            "Content-Type",
            "Origin",
            "X-Requested-With",
            "X-Workspace-Token",
        ],
    )

    @app.exception_handler(Exception)
    async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
        # CORSMiddleware does not attach Access-Control-* headers to a
        # response generated by Starlette's default 500 path, so a
        # crash in any handler shows up in the browser as
        # net::ERR_FAILED instead of "500 Internal Server Error".
        # We catch every uncaught exception, log the traceback, and
        # echo the request's Origin back if it is in the allowlist so
        # the frontend can read the JSON body and toast it.
        log.error(
            "Unhandled exception on %s %s: %s\n%s",
            request.method,
            request.url.path,
            exc,
            "".join(traceback.format_exception(exc)),
        )
        origin = request.headers.get("origin")
        headers: dict[str, str] = {}
        if origin and ("*" in allowed_origins or origin in allowed_origins):
            headers["access-control-allow-origin"] = origin
            headers["access-control-allow-credentials"] = "true"
            headers["vary"] = "Origin"
        body = {"detail": "Internal server error."}
        if settings.CHECKWISE_ENV == "local":
            body["error"] = f"{type(exc).__name__}: {exc}"
        return JSONResponse(status_code=500, content=body, headers=headers)

    @app.api_route("/", methods=["GET", "HEAD"], include_in_schema=False)
    def root() -> RedirectResponse:
        # When docs are disabled (prod default) point the bare-host hit
        # at /health instead of a 404'd /docs.
        return RedirectResponse(url="/docs" if docs_on else "/health")

    @app.get("/health", tags=["system"])
    def health() -> dict[str, str]:
        return {"status": "ok", "service": "checkwise-api", "environment": settings.CHECKWISE_ENV}

    app.include_router(api_router, prefix=settings.API_V1_PREFIX)
    _assert_critical_routes(app)
    return app


app = create_app()
