export const loadTypes = [
  { value: "alta_inicial", label: "Alta inicial" },
  { value: "contrato", label: "Contrato" },
  { value: "mensual", label: "Mensual" },
  { value: "bimestral", label: "Bimestral" },
  { value: "cuatrimestral", label: "Cuatrimestral" },
  { value: "anual", label: "Anual" },
  { value: "renovacion", label: "Renovación" },
  { value: "evento", label: "Evento / excepción" },
];

export const institutions = [
  { value: "stps_repse", label: "STPS / REPSE" },
  { value: "sat", label: "SAT" },
  { value: "imss", label: "IMSS" },
  { value: "infonavit", label: "INFONAVIT" },
  { value: "interno_cliente", label: "Interno / Cliente" },
];

export const requirementGuides = [
  {
    name: "Constancia de Situación Fiscal / RFC del proveedor",
    institution: "SAT",
    risk: "Alto",
    frequency: "Alta inicial",
    why: "Sirve para homologar RFC, razón social y datos fiscales contra contrato y facturas.",
    validExample: "PDF vigente descargado del SAT, legible y correspondiente al proveedor.",
    rejectionCauses: ["RFC distinto", "archivo ilegible", "documento de otro proveedor"],
  },
  {
    name: "Constancia REPSE vigente",
    institution: "STPS / REPSE",
    risk: "Crítico",
    frequency: "Alta inicial / renovación",
    why: "Acredita que el proveedor está registrado para prestar servicios especializados.",
    validExample: "Constancia REPSE en PDF con folio, vigencia, actividad y RFC visibles.",
    rejectionCauses: ["folio vencido", "actividad no relacionada", "PDF bloqueado"],
  },
  {
    name: "Contrato firmado",
    institution: "Interno / Cliente",
    risk: "Crítico",
    frequency: "Contrato",
    why: "Conecta el servicio contratado con proveedor, cliente, vigencia y actividad REPSE.",
    validExample: "Contrato completo firmado por las partes, en PDF legible.",
    rejectionCauses: ["sin firmas", "vigencia ausente", "objeto de servicio ambiguo"],
  },
  {
    name: "CFDI/XML de factura de servicio",
    institution: "SAT",
    risk: "Alto",
    frequency: "Mensual / por pago",
    why: "Permite cruzar RFCs, concepto, monto, IVA, periodo y contrato.",
    validExample: "Representación PDF de factura o acuse relacionado con el servicio del periodo.",
    rejectionCauses: ["periodo incorrecto", "RFC distinto", "concepto no relacionado"],
  },
  {
    name: "CFDI/XML de nómina trabajadores asignados",
    institution: "SAT",
    risk: "Crítico",
    frequency: "Mensual",
    why: "Soporta el cruce laboral/fiscal de trabajadores asignados al servicio especializado.",
    validExample: "PDF legible del comprobante o resumen de nómina del periodo.",
    rejectionCauses: ["periodo incorrecto", "trabajadores no identificables", "archivo bloqueado"],
  },
  {
    name: "Opinión de cumplimiento SAT positiva",
    institution: "SAT",
    risk: "Alto",
    frequency: "Alta inicial / mensual operativo",
    why: "Control preventivo fiscal para detectar riesgos ante SAT.",
    validExample: "PDF de opinión positiva con RFC, fecha y resultado visibles.",
    rejectionCauses: ["opinión negativa", "fecha vencida", "RFC distinto"],
  },
  {
    name: "Opinión de cumplimiento IMSS positiva",
    institution: "IMSS",
    risk: "Alto",
    frequency: "Alta inicial / mensual operativo",
    why: "Control preventivo de cumplimiento de seguridad social.",
    validExample: "PDF de opinión positiva con registro/RFC y fecha visibles.",
    rejectionCauses: ["opinión negativa", "registro patronal distinto", "archivo ilegible"],
  },
  {
    name: "Pago cuotas obrero-patronales IMSS",
    institution: "IMSS",
    risk: "Alto",
    frequency: "Mensual",
    why: "Permite verificar cumplimiento de cuotas relacionadas con trabajadores.",
    validExample: "Acuse o pago IMSS en PDF correspondiente al periodo.",
    rejectionCauses: ["periodo incorrecto", "registro patronal no coincide", "monto ilegible"],
  },
  {
    name: "Pago aportaciones/amortizaciones INFONAVIT",
    institution: "INFONAVIT",
    risk: "Alto",
    frequency: "Bimestral visible mensual",
    why: "Soporta cumplimiento de aportaciones y amortizaciones ante INFONAVIT.",
    validExample: "Acuse/pago INFONAVIT PDF correspondiente al bimestre aplicable.",
    rejectionCauses: ["bimestre incorrecto", "RFC distinto", "PDF sin texto legible"],
  },
  {
    name: "ICSOE IMSS",
    institution: "IMSS",
    risk: "Crítico",
    frequency: "Cuatrimestral",
    why: "Informativa cuatrimestral asociada a contratos, trabajadores y servicios especializados.",
    validExample: "Acuse ICSOE en PDF del cuatrimestre correspondiente.",
    rejectionCauses: ["cuatrimestre incorrecto", "acuse incompleto", "cliente/proveedor no coincide"],
  },
  {
    name: "SISUB INFONAVIT",
    institution: "INFONAVIT",
    risk: "Crítico",
    frequency: "Cuatrimestral",
    why: "Informativa cuatrimestral INFONAVIT para servicios especializados.",
    validExample: "Acuse SISUB en PDF del cuatrimestre correspondiente.",
    rejectionCauses: ["cuatrimestre incorrecto", "acuse incompleto", "registro no coincide"],
  },
  {
    name: "Renovación REPSE",
    institution: "STPS / REPSE",
    risk: "Crítico",
    frequency: "Cada 3 años",
    why: "Controla continuidad de elegibilidad REPSE y evita vencimientos críticos.",
    validExample: "Nueva constancia o renovación REPSE en PDF con vigencia visible.",
    rejectionCauses: ["folio vencido", "actividad no autorizada", "documento de otro proveedor"],
  },
];

export const requirements = requirementGuides.map((requirement) => requirement.name);
